# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_aboutus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aboutus',
        ),
    ]
