# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descrip', models.TextField()),
                ('img', models.CharField(max_length=100)),
            ],
        ),
    ]
