# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.FileField(upload_to=''),
        ),
    ]
