# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20170702_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(upload_to='team/'),
        ),
    ]
