# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20170702_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='descrip',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
    ]
