# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20170702_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='descrip',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
