# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20170702_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsdata',
            name='img_name',
        ),
        migrations.AddField(
            model_name='newsdata',
            name='img',
            field=models.ImageField(default=1, upload_to='news/'),
            preserve_default=False,
        ),
    ]
