# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20170702_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
