# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20170702_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsdata',
            name='monitoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsdata',
            name='slider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reference',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='source',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='fb',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
