# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20170705_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('descrip', models.TextField()),
                ('img', models.ImageField(upload_to='partners/')),
            ],
        ),
    ]
