# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_auto_20170715_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsdata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='newsdata',
            name='updated_at',
        ),
    ]
